apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            default_type "text/html";

            content_by_lua_block {
                ngx.say("<html><body>VSF</body></html>")
            }
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/local/openresty/nginx/html;
        }

        location /healthz {
            return 200 "OK";
        }
    }
