apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    {{- include "vsf-live-coding.labels" . | nindent 4 }}
    app.kubernetes.io/name:  vsf
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
